spring:
  profiles:
    active: dev
  application:
    name: antivirus-service
  config:
    import: optional:file:../.env[.properties]

  # === Kafka Configuration ===
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: antivirus-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.resume.common.model"

server:
  port: 8081

# === Yandex Object Storage ===
yandex:
  storage:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    endpoint: https://storage.yandexcloud.net
    region: ru-central1
    bucketName: first-aws-bucket

# === Kafka Topics ===
kafka:
  topics:
    file-upload-events: file-upload-events
    file-scan-results: file-scan-results
    file-upload-events-dlt: file-upload-events.DLT
  retry:
    max-attempts: 3         # Кол-во попыток
    backoff-delay: 10000    # 10 секунд — начальная задержка
    multiplier: 2.0         # Множитель: 10s → 20s → 40s
    max-interval: 60000     # 60 секунд — максимальная задержка
