spring:
  kafka:
    bootstrap-servers: kafka:9092

# === ClamAV (production) ===
clamav:
  host: clamav
  port: 3310

# === Logging (minimal) ===
logging:
  level:
    root: WARN
    org.resume.fileantivirusservice: INFO
    org.springframework.security: WARN