# === Spring Configuration ===
spring:
  application:
    name: S3FileManager
  profiles:
    active: dev
  config:
    import: optional:file:../.env[.properties]

  jpa:
    hibernate:
      ddl-auto: none

  # === Flyway ===
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  # === Kafka Configuration ===
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: s3-file-manager-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.resume.common.model"

# === Yandex Object Storage ===
yandex:
  storage:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    endpoint: https://storage.yandexcloud.net
    region: ru-central1
    bucketName: first-aws-bucket

# === Application Configuration ===
app:
  pageable:
    default-page-size: 20
    max-page-size: 100

  jwt:
    secretKey: ${JWT_SECRET_KEY}
    expiration: 86400  # 24h

  admin:
    name: ${ADMIN_NAME}
    password: ${ADMIN_PASSWORD}

  multiple-upload:
    max-batch-size: 5

# === Kafka Topics ===
kafka:
  topics:
    file-upload-events: file-upload-events
    file-scan-results: file-scan-results
    file-upload-events-dlt: file-upload-events.DLT
  retry:
    max-attempts: 3         # Кол-во попыток
    backoff-delay: 10000    # 10 секунд — начальная задержка
    multiplier: 2.0         # Множитель: 10s → 20s → 40s
    max-interval: 60000     # 60 секунд — максимальная задержка